#- name: check key file exists
#  stat:
#    path: "{{ identity_keypair_location }}"
#  register: keyfile
#  failed_when: not keyfile.stat.exists

- name: check disks exist
  become: true
  become_user: root
  shell: fdisk -l | grep 'Disk {{ item }}'
  with_items:
    - "{{ raw_disk_list }}"
  when: setup_disks is defined and (setup_disks | bool)
